USE jul_11;
CREATE TABLE ORDER_INFO (ID INT,ORDER_NAME VARCHAR(10),COST INT,ORDER_ID INT PRIMARY KEY,CREATED_AT TIMESTAMP,CREATED_BY VARCHAR(20),
    MODIFIED_AT TIMESTAMP,MODIFIED_BY VARCHAR(20));
    
    SELECT * FROM ORDER_INFO;
    
 CREATE TABLE PAYMENT_INFO (ID INT,PRICE DOUBLE,PAYMENT_ID INT PRIMARY KEY,ORDER_ID INT,PAYMENT_STATUS ENUM('ONLINE', 'OFFLINE'),
     CREATED_AT TIMESTAMP,CREATED_BY VARCHAR(20),MODIFIED_AT TIMESTAMP,MODIFIED_BY VARCHAR(20),FOREIGN KEY (ORDER_ID) REFERENCES ORDER_INFO(ORDER_ID));

SELECT * FROM PAYMENT_INFO;

CREATE TABLE RESTAURANT_INFO (ID INT,RESTAURANT_NAME VARCHAR(20),RESTAURANT_ID INT PRIMARY KEY,LOC VARCHAR(20),ORDER_ID INT,RATINGS INT ,PAYMENT_ID INT,
     CREATED_AT TIMESTAMP,CREATED_BY VARCHAR(20),MODIFIED_AT TIMESTAMP,MODIFIED_BY VARCHAR(20),FOREIGN KEY (ORDER_ID) REFERENCES ORDER_INFO(ORDER_ID),
     FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT_INFO(PAYMENT_ID));
     
     SELECT * FROM RESTAURANT_INFO;

CREATE TABLE DELIVERY_INFO (ID INT,PERSON_NAME VARCHAR(20),MODE_OF_PAYMENT ENUM('ONLINE', 'OFFLINE'), RESTAURANT_ID INT,ORDER_ID INT,
     CREATED_AT TIMESTAMP,CREATED_BY VARCHAR(20),MODIFIED_AT TIMESTAMP,MODIFIED_BY VARCHAR(20),FOREIGN KEY (ORDER_ID) REFERENCES ORDER_INFO(ORDER_ID),
     FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT_INFO(RESTAURANT_ID));
     
     SELECT * FROM DELIVERY_INFO;
     
      INSERT INTO ORDER_INFO(ID,ORDER_NAME,COST,ORDER_ID,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) VALUES (1,'RAM',200,542,NOW(),'ARUN',NOW(),'RAJ');
      INSERT INTO ORDER_INFO(ID,ORDER_NAME,COST,ORDER_ID,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) VALUES (2,'GEETHA',250,543,NOW(),'MONOJ',NOW(),'RAJU');
      INSERT INTO ORDER_INFO(ID,ORDER_NAME,COST,ORDER_ID,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) VALUES (3,'ANUSHA',2000,544,NOW(),'GAGAN',NOW(),'DEV');

 INSERT INTO PAYMENT_INFO (ID,PRICE,PAYMENT_ID,ORDER_ID,PAYMENT_STATUS,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) VALUES  (1,300,100,542,1,NOW(),'RAJU',NOW(),'RAMU');
 INSERT INTO PAYMENT_INFO (ID,PRICE,PAYMENT_ID,ORDER_ID,PAYMENT_STATUS,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) VALUES  (2,400,101,543,2,NOW(),'RAJ',NOW(),'RAM');
 INSERT INTO PAYMENT_INFO (ID,PRICE,PAYMENT_ID,ORDER_ID,PAYMENT_STATUS,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) VALUES  (3,350,102,544,1,NOW(),'MANU',NOW(),'ANAD');

INSERT INTO RESTAURANT_INFO(ID,RESTAURANT_NAME,RESTAURANT_ID,LOC,ORDER_ID,RATINGS,PAYMENT_ID,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) 
VALUES (1,'RAMA HOTEL',301,'HASSAN',542,5,100,NOW(),'SADHASHIVA',NOW(),'SHANKAR');
INSERT INTO RESTAURANT_INFO(ID,RESTAURANT_NAME,RESTAURANT_ID,LOC,ORDER_ID,RATINGS,PAYMENT_ID,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) 
VALUES (2,'MERIDEAN ',302,'HASSAN',543,6,102,NOW(),'SHIVKUMAR',NOW(),'SHANKAR A.J.');

INSERT INTO DELIVERY_INFO(ID,PERSON_NAME,MODE_OF_PAYMENT,RESTAURANT_ID ,ORDER_ID,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) VALUES
(1,'MOHAN',2,301,542,NOW(),'SINDHU',NOW(),'NITHYA');
INSERT INTO DELIVERY_INFO(ID,PERSON_NAME,MODE_OF_PAYMENT,RESTAURANT_ID ,ORDER_ID,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) VALUES
(2,'POORNA',1,302,543,NOW(),'POOJA',NOW(),'SAHANA');
